// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlHeXDaOli9F31P8KZDnN9V4XZKmBzPRY',
    appId: '1:1097496596606:web:cd5ece05d4e0270b56482f',
    messagingSenderId: '1097496596606',
    projectId: 'uthm-hub',
    authDomain: 'uthm-hub.firebaseapp.com',
    storageBucket: 'uthm-hub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgdIb9qKgQtMzRVPQxw0zCQQt_qJbc_4k',
    appId: '1:1097496596606:android:bcceb637b6332d1556482f',
    messagingSenderId: '1097496596606',
    projectId: 'uthm-hub',
    storageBucket: 'uthm-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuO63ub-nwLky908MpY8y4cwj002rYruo',
    appId: '1:1097496596606:ios:bbd3a1a94c3fd16656482f',
    messagingSenderId: '1097496596606',
    projectId: 'uthm-hub',
    storageBucket: 'uthm-hub.firebasestorage.app',
    iosBundleId: 'com.example.uthmHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuO63ub-nwLky908MpY8y4cwj002rYruo',
    appId: '1:1097496596606:ios:bbd3a1a94c3fd16656482f',
    messagingSenderId: '1097496596606',
    projectId: 'uthm-hub',
    storageBucket: 'uthm-hub.firebasestorage.app',
    iosBundleId: 'com.example.uthmHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlHeXDaOli9F31P8KZDnN9V4XZKmBzPRY',
    appId: '1:1097496596606:web:3acd3d848015f00c56482f',
    messagingSenderId: '1097496596606',
    projectId: 'uthm-hub',
    authDomain: 'uthm-hub.firebaseapp.com',
    storageBucket: 'uthm-hub.firebasestorage.app',
  );
}
